### ISSUE TITLE
Setting `globals` override doesn't work with comments on the same line as the variable

### ISSUE THREAD

**Issue by artemreyt** [lunarmodules/luacheck#12]
Here is example of code:
```
global_number = io.read("number") -- luacheck: globals global_number

global_number = global_number * 2
if global_number > 0 then
    print("Positive")
else
    print("Non-positive")
end
```
Run luacheck: 
```
$ luacheck --codes globals_luacheck.lua
Checking globals_luacheck.lua                     3 warnings

    globals_luacheck.lua:3:1: (W111) setting non-standard global variable global_number
    globals_luacheck.lua:3:17: (W113) accessing undefined variable global_number
    globals_luacheck.lua:4:4: (W113) accessing undefined variable global_number

Total: 3 warnings / 0 errors in 1 file
```

It will be ok if to place `-- luacheck: globals global_number` on the line before declaring `global_number`, but our code style tells to add inline options on the same line with code. Other inline command work in this way.

Created the same [issue](https://github.com/mpeterv/luacheck/issues/210) in original repo.

**Comment by nvs** [comment]
The documentation on this seems fairly clear (see https://luacheck.readthedocs.io/en/stable/inline.html):

> Part of the file affected by inline option dependes on where it is placed. If there is any code on the line with the option, only that line is affected; otherwise, everything till the end of the current closure is. In particular, inline options at the top of the file affect all of it:

Thus the expected behavior is encountered in the example above.

**Comment by alerque** [comment]
As @nvs notes, this is expected and documented behavior. Note the warning is not being thrown for L1 in your example, only L3. If you want to ignore a global either add a comment at the correct closure or file level (rather than inline) or add it to your `.luacheckrc` file.
