### ISSUE TITLE
Claim project to get coverage reporting

### ISSUE THREAD

**Issue by alerque** [lunarmodules/luacheck#28]
Hey @hishamhm can you either click on the claim button on [this page](https://coveralls.io/github/lunarmodules/luacheck/settings) or give me another bump to owner status on this repo? I think that will make coverage reporting start working with no other changes, but it won't let me do it.

![image](https://user-images.githubusercontent.com/173595/136379028-55bce91e-2798-4823-9d77-68639a3cc10a.png)

**Comment by alerque** [comment]
While you are there lets also set the min target threshold to 95% (current actual is 96%) and the decrease for warnings to 1% or something like that. Otherwise it errors on 0.01% decreases and those are easy to trip just by editing comments without actually changing code.

**Comment by hishamhm** [comment]
I clicked on "Claim" and it showed this:

![image](https://user-images.githubusercontent.com/245621/137196064-09f621b7-de6c-4014-8d05-479999cd0395.png)

but the "Sync" button still causes an error:

![image](https://user-images.githubusercontent.com/245621/137196137-da3fc8da-d22b-4405-ac0b-b2d26efd0001.png)

I added you as "Admin" in the Settings tab for this repo, but I see no "Owner" option?
