### ISSUE TITLE
Check Lua code passed to loadstring()

### ISSUE THREAD

**Issue by ligurio** [lunarmodules/luacheck#36]
Lua has the `loadstring` function, which parses a string and returns a function that would execute that code, provided the given string is a syntactically correct Lua function body. See [1], [2].

I think it would be useful to check Lua code passed to `loadstring` with Luacheck.

1. https://www.lua.org/manual/5.1/manual.html#pdf-loadstring
2. https://www.lua.org/pil/8.html

**Comment by alerque** [comment]
It's possible it would be useful, but I believe this would require *evaluating* Lua code. That opens a whole can of worms that is probably outside the scope of this project.

An analgous example, if you lint a file with Luacheck and it has a `require("other.module")` call in it, we are just linting the lexical syntax of that command. We don't evaluate the require statement, use the package.path, load the module, and lint it. We just work with the syntax and parsed ast tree of the Lua grammar.

If I'm missing something here feel free to chime back in and we can re-evaluate.
