### ISSUE TITLE
Document new_globals and new_read_globals

### ISSUE THREAD

**Issue by idbrii** [lunarmodules/luacheck#40]
[Custom sets of globals](https://luacheck.readthedocs.io/en/stable/config.html?#custom-sets-of-globals) describes globals and read_globals:

```lua
   globals = {"foo", "bar"}, -- these globals can be set and accessed.
   read_globals = {"baz", "quux"} -- these globals can only be accessed.
```

It later mentions the new_ variables:

> In config, globals, new_globals, read_globals, and new_read_globals can also contain definitions in same format:

But doesn't explain what they do.

I would guess these are their purpose:

*   globals -- these globals can be set and accessed.
*   read_globals -- these globals can only be accessed.
*   new_globals -- these globals can be set but not accessed.
*   new_read_globals -- these globals can be set and accessed.

However, that means globals and new_read_globals are the same. Possibly, "new_" means to append to another list -- use these globals in addition to std?

Also, [Config options](https://luacheck.readthedocs.io/en/stable/config.html?#config-options) says:

<html>
<body>

Option | Type | Default value
-- | -- | --
new_globals | Array of strings or field definition map | (Do not overwrite)
new_read_globals | Array of strings or field definition map | (Do not overwrite)

<br class="Apple-interchange-newline">
</body>
</html>

Which maybe means I shouldn't set the new_ variables? Why are they there?

*(Migrated from mpeterv/luacheck/issues/217)*

**Comment by arichard4** [comment]
This seems to be effectively undocumented.

Luacheck supports [per-path and per-file override options](https://luacheck.readthedocs.io/en/stable/config.html#per-file-and-per-path-overrides). These can be nested in an arbitrary depth. The original intent was definitely for "new_globals" to *override* any existing/project-wide globals; see [this commit](https://github.com/lunarmodules/luacheck/commit/d884ef1328a66bef81ddb69fff93b0ee5381ba73). Note that *new_globals* doesn't get overridden by later new_globals.

A simple test:

```
mkdir test
cd test
echo 'globals = {"x"}; files["test.lua"] = {new_globals = {"y"}}' > .luacheckrc
echo 'x = 3' > test.lua
luacheck .
> Checking test.lua                                 1 warning
> 
>     test.lua:1:1: setting non-standard global variable x
> 
> Total: 1 warning / 0 errors in 1 file
```

**Comment by idbrii** [comment]
Thanks for the explanation.

What do you mean by:

> Note that new_globals doesn't get overridden by later new_globals.

Seems like new_globals always overrides previous globals:

```lua
mkdir -p test/lib
cd test
echo 'files["lib/"] = {new_globals = {"x"}}; files["lib/test.lua"] = {new_globals = {"y"}}' > .luacheckrc
echo 'x = 3' > lib/test.lua
luacheck .

> Checking lib\test.lua                             1 warning
> 
>     lib\test.lua:1:1: setting non-standard global variable 'x'
> 
> Total: 1 warning / 0 errors in 1 file
```

Removing the `files["lib/test.lua"]`  line makes the warning go away (on Luacheck: 0.23.0).


> This seems to be effectively undocumented.

I'll rename the issue accordingly.

**Comment by arichard4** [comment]
Ooops, yeah, you're right, I had misunderstood myself. Anyways, I'll go use my obviously excellent understanding of how this works to write up some documentation.

**Comment by arichard4** [comment]
The documentation at https://luacheck.readthedocs.io/ is still pointing at Peter's repository; I will try to get it to point at this repo instead.

**Comment by arichard4** [comment]
Hey @daurnimator, as I understand it you currently control the readthedocs page- mind changing it to point at this repo? That should also hopefully cause people to start reporting bugs in the right place, since the 0.24 release updates the URLs.

**Comment by daurnimator** [comment]
I've pointed at this repo. Anything else need to be done?

**Comment by arichard4** [comment]
Not from you, looks like the docs are updated for 0.25. Thanks!
