### ISSUE TITLE
lua5.4 <close> variable 

### ISSUE THREAD

**Issue by xiyoo0812** [lunarmodules/luacheck#44]
function tt(k)
     local lock\<close\> = thread_mgr:lock(k)
     ....
end

 unused variable 'lock'

**Comment by arichard4** [comment]
Can you clarify? (Do you expect unused variables with the close attribute to not be flagged as being unused?)

**Comment by xiyoo0812** [comment]
yes，Thank you for your reply，This is a general usage, similar to the lock destructor of C++。

**Comment by nvs** [comment]
If the variable is not going to be used, then the `_` identifier could be utilized. Also, as introduced in PR #24, one can now also prefix the identifier with an underscore (although this change is not live in the version on LuaRocks):

```lua
function tt(k)
    local _ <close> = thread_mgr:lock(k)
    local _lock <close> = thread_mgr:lock(k)
    --
end
```

Luacheck will have the hint that these variables are to be unused. And should they start being used it will notify of their usage, at which point the underscore can be removed.

**Comment by xiyoo0812** [comment]
> If the variable is not going to be used, then the `_` identifier could be utilized. Also, as introduced in PR #24, one can now also prefix the identifier with an underscore (although this change is not live in the version on LuaRocks):
> 
> ```lua
> function tt(k)
>     local _ <close> = thread_mgr:lock(k)
>     local _lock <close> = thread_mgr:lock(k)
>     --
> end
> ```
> 
> Luacheck will have the hint that these variables are to be unused. And should they start being used it will notify of their usage, at which point the underscore can be removed.

ok，it’s good！

**Comment by nvs** [comment]
@xiyoo0812 

I believe I was wrong on the second point above (I crossed it out). I misunderstood the scope of the changes, and they seem to only apply to function arguments. As in the following:

```lua
local function f(_unused)
end
```

However, using `_` will still work as I described. Sorry for the mix up.
