### ISSUE TITLE
Update readthedocs.io documentation

### ISSUE THREAD

**Issue by alerque** [lunarmodules/luacheck#58]
I kind of expected RTD to update automatically when we tagged a release, but https://luacheck.readthedocs.io/ is still only showing the 0.25.0 release and I'm not sure how it is supposed to be triggered, nor who set it up. @daurnimator is that you?

It may be because of the repository migration which happened after the last release or it could be because I started using a `v` prefix on the release tags.

**Comment by daurnimator** [comment]
I set it up originally but it seems it came undone?
In any case, I set up the integration again (following instructions at https://docs.readthedocs.io/en/stable/integrations.html#github ).

FYI @alerque you'll need a read-the-docs account if you want me to add you as a maintainer over there.

**Comment by alerque** [comment]
@daurnimator Sure, account name is the same as here: https://readthedocs.org/profiles/alerque/

**Comment by daurnimator** [comment]
Done.
