### ISSUE TITLE
Warning 214 and _ENV

### ISSUE THREAD

**Issue by hugomg** [lunarmodules/luacheck#62]
Starting with Luacheck 0.26, I get a warning if I explicitly use an _ENV variable. For example:

```lua
-- test.lua
return function(_ENV)
    local it = _ENV.it
    return it
end
```

```sh
$ luacheck test.lua
Checking test.lua                                 1 warning

    test.lua:1:17: used variable _ENV

Total: 1 warning / 0 errors in 1 file
```

A similar thing happens with other special names that start with underscore.

```lua
return function(_VERSION)
    return _VERSION
end
return function(_G)
    return _G
end
```

If I understand it correctly, the issue is that Luacheck started assuming that 
1. By default, a variable name starting with "_" is a hint that the variable is unused.
2. Using a variable that was marked with such a hint now produces warning 214.

Assumption (1) seems reasonable. Oftentimes we only declare an _ENV variable for its implicit magic effects, and a variable called _G might really be an "unusified" version of "G". My suggestion then would be to add an exception for warning 214, not producing a warning when the variable name is one of these special ones.

**Comment by alerque** [comment]
Good call, we do need an exception list. Do you happen to know of a canonical one and if there are variations across lua versions? Since we have that as part of our configuration we do need to account for what versions have what special variables...

**Comment by hugomg** [comment]
Honestly, I think the `_ENV` is the only variable that absolutely needs to bypass the 214 warning. It is the only time where the name of a local variable matters. Every other time the programmer has the option of renaming the variable to something without an underscore

If we want to be less strict than this, perhaps ignore the warning for any of the special names listed in [builtins_standard](https://github.com/lunarmodules/luacheck/tree/master/src/luacheck/builtin_standards) (namely: _G, _VERSION, _ENV). Or maybe ignore the warning for anything that is in ALL CAPS.

**Comment by alerque** [comment]
In setting up a test to show that this is a problem (prerequisite for fixing it) I realized this is not *quite* as much of as issue as I thought. This warning case is only being thrown if you explicitly name an argument to your own function using something that shadows a builtin global. Just *using* these globals doesn't trigger a warning, only using them in the case where they have been shadowed does. That seems like something that *should* be triggering a warning. Maybe a different more clear warning..

Thoughts?

**Comment by hugomg** [comment]
With _ENV, I think there is some legitimate use. When you use _ENV, you're going to be redeclaring it as a local and it must have this exact name to do its job.

I agree that for other names it is more contrived. I think it would be reasonable to only special case _ENV.

**Comment by hugomg** [comment]
To be clear, I don't think we need a new warning. Maybe just tweak the error message for 214 a bit, to clarify that the reason for the warning is because you're uhesing a variable was marked as unused.

Additionaly, I think we should add an exception for _ENV and not have it trigger warning 214. For other variables we can leave it as it is now, because the programmer has the option of renaming it to something else to avoid the warning.

**Comment by hugomg** [comment]
Thanks!
