### ISSUE TITLE
Cache invalidation on version change

### ISSUE THREAD

**Issue by Zash** [lunarmodules/luacheck#69]
1. Install older version of luacheck
2. Use it for a while
3. Upgrade luacheck
4. Observe no new warnings
5. Touch a random file
6. Suddenly warnings for that file
7. Wipe `~/.cache/luacheck`
8. **SO MANY WARNINGS**

Perhaps mixing the version number into the cache key would help invalidate the caches upon upgrade?

**Comment by alerque** [comment]
Yes, this is probably a good idea.
