### ISSUE TITLE
Error in config file when there is no config file

### ISSUE THREAD

**Issue by tomasguisasola** [lunarmodules/luacheck#78]
Hi guys,

First of all, I very much appreciate your efforts on luacheck!

I have just updated to release 1.0.0 and now when I run luacheck it complains with the message:

   "Critical error: in config loaded from .luacheckrc: invalid options for path '**/config.ld': invalid value of option 'std': unknown std 'ldoc'"

This happens to whatever file I try to check.

Regards,
Tomás

**Comment by alerque** [comment]
How did you install Luacheck? It sounds like you're using a distribution that somehow doesn't have the new files packaged.

**Comment by tomasguisasola** [comment]
I used LuaRocks.  What differs from standard is that I install all rocks in a particular tree (not /usr/local/ nor ~/.luarocks)  Does it make any difference?

**Comment by alerque** [comment]
No the target tree shouldn't make a difference when installing directly with `luarocks`.

**Comment by alerque** [comment]
I can't replicate this anywhere.

What does your project's `.luacheckrc` look like?

**Comment by tomasguisasola** [comment]
I don't have a `.luacheckrc`

**Comment by alerque** [comment]
Is it possible that your system has two `luacheck` installations, one in your private tree (wherever that is) and one in a more common location like the system or default user install locations — and that when you run Luacheck you are invoking one but your path is messed up and it is finding supporting files from the *other* installation and hence mixing and matching sources?

**Comment by tomasguisasola** [comment]
I removed all previous versions of luacheck (all of them were installed via LuaRocks) and now it is running ok.  Thanks!
