### ISSUE TITLE
require/io/os/print/table - accessing undefined variable require

### ISSUE THREAD

**Issue by Lilja** [lunarmodules/luacheck#81]
I'm new to lua and wanted to lint/check my neovim plugin that is written in lua.

I have this file:
```lua
-- lua/zellij/health.lua  
local zellij = require("zellij")
```

When I lint it:
```
Checking lua/zellij/health.lua                    1 warning

    lua/zellij/health.lua:1:16: accessing undefined variable require
```

My configuration: `luacheck ./lua --config ./luacheckrc`

```
std = { globals = {"vim"}, }
```

The same thing happens for `io`, `print`, `error`, `table`, `os`. Why is this happening? Are those APIs not part of the lua specification?

`lua -v`: `Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio`
`luachecks --version`:
```
Luacheck: 1.0.0
Lua: PUC-Rio Lua 5.4
Argparse: 0.7.1
LuaFileSystem: 1.[8](https://github.com/Lilja/zellij.nvim/actions/runs/3384443048/jobs/5621410801#step:7:9).0
LuaLanes: Not found
```

**Comment by alerque** [comment]
Your luacheckrc file is messed up. You are killing off all the standard globals (which include things like core Lua language functions). I think you need something more like this:

```lua
std = "luajit"
globals = { "vim" }
```

This will load the presets Lua most similar to the version NeoVIM embeds, then add the `vim` global into the mix.

**Comment by Lilja** [comment]
@alerque Legend! Thanks for taking some time to help me.
