### ISSUE TITLE
how to use --exclude-files in cmd line

### ISSUE THREAD

**Issue by tweyseo** [lunarmodules/luacheck#85]
i use 
```
luacheck --std=luajit+ngx_lua --globals=ETCRS --no-max-line-length --exclude-files "test1.lua"  test2.lua
```
it returns "Error: missing argument 'files'"

**Comment by alerque** [comment]
You aren't passing any files to me checked. Because `--exclude-files` takes a glob which can be more than one file, everything after it (both test1.lua and test2.lua) is being interpreted as things to exclude. Nowhere in your command are you passing in anything to actually **include**. Try adding `.` with an argument separator at the end:

```console
$  luacheck --std=luajit+ngx_lua --globals=ETCRS --no-max-line-length --exclude-files test1.lua  test2.lua -- .
```

**Comment by tweyseo** [comment]
no error return, but it seems option "-exclude-files" not worked:
```
PS D:\Program Files\Lua\luacheck> .\luacheck.exe --std=luajit+ngx_lua --globals=ETCRS --no-max-line-length --exclude-files test1.lua -- E:\tweyseo\stdio\xproject\.
Checking E:\tweyseo\stdio\xproject\.\test1.lua 1 warning

    E:\tweyseo\stdio\xproject\.\test1.lua:1:7: unused variable 'a'

Checking E:\tweyseo\stdio\xproject\.\test2.lua OK
Checking E:\tweyseo\stdio\xproject\.\test3.lua OK
Checking E:\tweyseo\stdio\xproject\.\test4.lua OK

Total: 1 warning / 0 errors in 4 files
```
i was under windows and Luacheck: 0.23.0

**Comment by tweyseo** [comment]
no error return, but it seems option "-exclude-files" not worked:
```
PS D:\Program Files\Lua\luacheck> .\luacheck.exe --std=luajit+ngx_lua --globals=ETCRS --no-max-line-length --exclude-files test1.lua -- E:\tweyseo\stdio\xproject\.
Checking E:\tweyseo\stdio\xproject\.\test1.lua 1 warning

    E:\tweyseo\stdio\xproject\.\test1.lua:1:7: unused variable 'a'

Checking E:\tweyseo\stdio\xproject\.\test2.lua OK
Checking E:\tweyseo\stdio\xproject\.\test3.lua OK
Checking E:\tweyseo\stdio\xproject\.\test4.lua OK

Total: 1 warning / 0 errors in 4 files
```
i was under windows and Luacheck: 0.23.0

**Comment by alerque** [comment]
I cannot replicate these results. However you are using a full path for the files to check and a local relative path for excludes. You may need to use either relative or absolute paths to both. Try changing into the directory you are checking first, don't run it from a location outside of the project you're testing.

It's also possible there is a path handling bug involved on the Windows side, but before we go down that rabbit hole please upgrade your `luacheck` version. You are 6 major releases behind, the current version in v1.1.0. I'm not interested in volunteering my time supporting a 4 year old release before I was even involved in the project.

**Comment by tweyseo** [comment]
thanks a lot, i'll try them all

**Comment by alerque** [comment]
Also review the output of `luarocks --version` and make sure the argparse library it finds is up to date (e.g. `0.7.1`).
