### ISSUE TITLE
how to filter file when specify files

### ISSUE THREAD

**Issue by tweyseo** [lunarmodules/luacheck#86]
i use following shell
```
CHANGE_FILES=$(git diff --name-only ${CI_COMMIT_BEFORE_SHA} ${CI_COMMIT_SHA})
luacheck --exclude-files **/test4.lua  -- $CHANGE_FILES
```
but $CHANGE_FILES will include other files that not end in `.lua`
neither i use `--exclude-files` nor `--include-files`, both doesn't work
so how can i filter out files not end in `.lua` here

**Comment by alerque** [comment]
Just filter your `CHANGE_FILES` before passing it. Explicit enumerated args are not meant to be overwritten with the filters, you need to tell it what to do correctly the first time.

```bash
CHANGE_FILES=$(git diff --name-only ${CI_COMMIT_BEFORE_SHA} ${CI_COMMIT_SHA} -- '*.lua')
luacheck --exclude-files **/test4.lua  -- $CHANGE_FILES
```
