### ISSUE TITLE
Luacheck isn't being installed properly on Fedora34 Docker image

### ISSUE THREAD

**Issue by kmezynski** [lunarmodules/luacheck#99]
### Testing setup
- geerlingguy/docker-fedora34-ansible:latest
- geerlingguy/docker-rockylinux8-ansible:latest

### Steps to reproduce
```bash
docker run -it geerlingguy/docker-fedora34-ansible:latest bash
yum install lua-devel luarocks gcc
luarocks install luacheck
luacheck
/usr/lib/luarocks/rocks-5.4/luacheck/1.1.1-1/bin/luacheck
```

### Observed behaviour
```bash
[root@b4b90dd62f3a /]# luacheck
bash: luacheck: command not found
```
```bash
[root@b4b90dd62f3a /]# /usr/lib/luarocks/rocks-5.4/luacheck/1.1.1-1/bin/luacheck
lua: /usr/lib/luarocks/rocks-5.4/luacheck/1.1.1-1/bin/luacheck:2: module 'luacheck.main' not found:
        no field package.preload['luacheck.main']
        no file '/usr/share/lua/5.4/luacheck/main.lua'
        no file '/usr/share/lua/5.4/luacheck/main/init.lua'
        no file '/usr/lib64/lua/5.4/luacheck/main.lua'
        no file '/usr/lib64/lua/5.4/luacheck/main/init.lua'
        no file './luacheck/main.lua'
        no file './luacheck/main/init.lua'
        no file '/root/.luarocks/share/lua/5.4/luacheck/main.lua'
        no file '/root/.luarocks/share/lua/5.4/luacheck/main/init.lua'
        no file '/usr/lib64/lua/5.4/luacheck/main.so'
        no file '/usr/lib64/lua/5.4/loadall.so'
        no file './luacheck/main.so'
        no file '/root/.luarocks/lib64/lua/5.4/luacheck/main.so'
        no file '/usr/lib64/lua/5.4/luacheck.so'
        no file '/usr/lib64/lua/5.4/loadall.so'
        no file './luacheck.so'
        no file '/root/.luarocks/lib64/lua/5.4/luacheck.so'
stack traceback:
        [C]: in function 'require'
        /usr/lib/luarocks/rocks-5.4/luacheck/1.1.1-1/bin/luacheck:2: in main chunk
        [C]: in ?
```

### Expected behaviour
`luacheck` binary is present in the default location `/usr/local` and there's no traceback while executing this binary.

### Notes
- Analogous steps on Debian and Ubuntu Docker images weren't observed (no traceback and `luacheck` is available under `/usr/local/bin/luacheck`).
- I've tried to install Lua and LuaRocks from the source on Fedora34 image, but then I've encountered a bit different behaviour that deserve its own issue.

**Comment by alerque** [comment]
I played around a little bit and did get the same results as you, but *only* with that Docker image. No other platforms seem to have this problem (luacheck has been installed from luarocks 2.8 million times). Many distros tested work just fine. Furthermore it isn't just this package, the luarocks on that Docker image is not installing *any* binaries. I tried half a dozen other Lua packages that place stuff in the LUA_BINDIR and *none* of them worked.

LuaRocks itself works just fine on many platforms and I don't see any obvious misconfiguration. My conclusion is that something weird is up with those images you are using, maybe some directory protection of funky mounts or something.

**Comment by kmezynski** [comment]
I checked and verified the behavior on Fedora images 33-39, including both the official ones and those provided by @geerlinguy. I can confirm that errors were observed in both cases for images with versions less than 35.

With that being said we can close the issue.

**Comment by alerque** [comment]
Thanks for the follow up. I assume if you really needed to get this working there is probably something in the 34→35 release as far as changes to LuaRocks or system level configs that could be backported for older versions too.
